[workspace]
members = [
    "configuration",
    "common",
    "mailer",
    "tokenizer",
    "modules/pg",
    "modules/auth",
    "modules/users",
    "modules/roles",
    "modules/tenants",
    "server"
]